version: '3.8'

services:
  inversionesji:
    image: frankecb04/inversiones-image
    ports:
      - "8080:8080"
    environment:
      SPRING_MONOLITO_DATASOURCE_URL: jdbc:postgresql://db:5432/InversionesJI
      SPRING_MONOLITO_DATASOURCE_USERNAME: postgres
      SPRING_MONOLITO_DATASOURCE_PASSWORD: admin

      SPRING_PROPIEDAD_DATASOURCE_URL: jdbc:postgresql://db:5432/PropiedadService
      SPRING_PROPIEDAD_DATASOURCE_USERNAME: postgres
      SPRING_PROPIEDAD_DATASOURCE_PASSWORD: admin
      PROPERTY_SERVICE_URL: http://propiedadservice:8083
    depends_on:
      - db
      - propiedadservice
    networks:
      - inversiones-network

  propiedadservice:
    image: frankecb04/propiedad-image
    ports:
      - "8083:8083"
    environment:
      SPRING_MICRO_DATASOURCE_URL: jdbc:postgresql://db:5432/PropiedadService
      SPRING_MICRO_DATASOURCE_USERNAME: postgres
      SPRING_MICRO_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    networks:
      - inversiones-network

  db:
    build:
      context: ./bd
      dockerfile: Dockerfile
    image: frankecb04/bd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - inversiones-network

volumes:
  postgres-data:

networks:
  inversiones-network:
    driver: bridge
