name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  fetch-ip:
    uses: ./.github/workflows/fetch_ec2_ip.yml

  deploy-inversiones:
    uses: ./.github/workflows/deploy_inversiones.yml
    needs: fetch-ip

  deploy-propiedad:
    uses: ./.github/workflows/deploy_propiedad.yml
    needs: fetch-ip

  deploy-bd:
    uses: ./.github/workflows/deploy_bd.yml
    needs: fetch-ip
