name: Deploy to EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch EC2 instance IP
        id: ec2_ip
        run: |
          INSTANCE_IP=$(terraform output -raw instance_ip | head -n 1)
          echo "Fetched IP: $INSTANCE_IP"
          echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV

      - name: SSH and deploy
        run: ssh ec2-user@${{ env.INSTANCE_IP }} -i ${{ secrets.EC2_SSH_KEY }} << 'EOF'
          cd /home/ec2-user
          sudo docker-compose down
          sudo rm -rf docker-compose-Microservice
          git clone https://github.com/Frankcb04/docker-compose-Microservice docker-compose-Microservice
          cd docker-compose-Microservice
          git pull origin master
          sudo docker-compose up -d --build
          
          # Puedes agregar más comandos según sea necesario después del despliegue
          
          # Ejemplo: mostrar información del sistema después del despliegue
          echo "Información del sistema:"
          uname -a
          
          # Ejemplo: listar los contenedores en ejecución
          echo "Contenedores en ejecución:"
          sudo docker ps
          EOF
