name: Deploy to EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch EC2 instance IP
        id: ec2_ip
        run: |
          INSTANCE_IP=$(terraform output -raw instance_ip | head -n 1)
          echo "Fetched IP: $INSTANCE_IP"
          echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: SSH and deploy
        env:
          INSTANCE_IP: ${{ steps.ec2_ip.outputs.INSTANCE_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${INSTANCE_IP} << 'EOF'
            cd /home/ec2-user || exit
            sudo docker-compose down
            sudo rm -rf docker-compose-Microservice
            git clone https://github.com/Frankcb04/docker-compose-Microservice docker-compose-Microservice
            cd docker-compose-Microservice || exit
            git pull origin master
            sudo docker-compose up -d --build
          EOF
